### ISSUE TITLE
'Convert Indentation to Spaces' and 'Convert Indentation to Tabs' do not work as expected

### ISSUE THREAD

**Issue by rkopicki** [coteditor/CotEditor#1923]
### Description

When `Settings… > Edit > Indentation: Prefer using` set to `Tabs`:
1. The `Text > Indentation > Convert Indentation to Spaces` does not seem to do anything, neither on the whole document nor on a selection. 
2. The `Text > Indentation > Convert Indentation to Tabs` does not work on the whole document (no selection) but converts whole document (outside of selection) when any selection made.

When `Settings… > Edit > Indentation: Prefer using` set to `Spaces`:
1. The `Text > Indentation > Convert Indentation to Spaces` does not work on the whole document (no selection) but converts whole document (outside of selection) when any selection made.
2. The `Text > Indentation > Convert Indentation to Tabs` does not seem to do anything, neither on the whole document nor on a selection. 

### To Reproduce

Please see above.

### Expected behavior

Expected result would be the lines’ indentation (leftmost whitespace) is converted from spaces to tabs or vice versa based on the tab width setting. When no selection is made, all lines should be processed. When the user selects text, e.g. a range of lines, the processing should be limited to the selection.

### CotEditor version

5.2.3 (730)

### macOS version

15.6.1 (24G90)

**Comment by 1024jp** [comment]
@rkopicki Thank you for the report!

This appears to be a bug. I’ve just fixed it and it will be included in CotEditor 6.0.0.

**Comment by rkopicki** [comment]
@1024jp Thank you for your prompt response!

**Comment by rkopicki** [comment]
@1024jp Unfortunately, 'Convert Indentation to Spaces' and 'Convert Indentation to Tabs' still do not work as expected. 😩

In version 6.0.0, both conversions do not work unless the user selects any text but then moves the cursor to the end of the document.

Expected behaviour would be that for no selection the whole document (all lines) is processed without changing (relative, i.e. visual) cursor position. If any lines are (even partially) selected, processing is limited to the selected lines without changing (relative) cursor position.

**Comment by 1024jp** [comment]
@rkopicki Ah, thank you for the check. I've just fixed it for CotEditor 6.0.1.
