### ISSUE TITLE
Unable to open CotEditor from CLI?

### ISSUE THREAD

**Issue by chrisbergeron** [coteditor/CotEditor#1979]
### Description

Attemtping to launch CotEditor from the Command LIne in Macos hangs. 

My primary use is invocation from the CLI.  If this by design, feel free to close this bug report.

### To Reproduce

Steps to reproduce:

1) Open Terminal
2) /Applications/CotEditor.app/Contents/MacOS/CotEditor

hang here - no app window opens

No security permission issue apparent in macos.

Permissions are correct:
```bash
$ ls -l /Applications/CotEditor.app/Contents/MacOS/
.rwxr-xr-x@ 13M username  8 Nov 20:02 CotEditor
```

### Expected behavior

<img width="752" height="832" alt="Image" src="https://github.com/user-attachments/assets/d7327a66-5584-4c96-8e7d-391428cb40b3" />

### CotEditor version

Version 6.1.1 (769)

### macOS version

15.6.1 (24G90)

**Comment by 1024jp** [comment]
@chrisbergeron Thank you for the report.
This is indeed unintended behavior...
It definitely needs fixing, but I haven't quite grasped the root cause yet, so it might take some time.
Please give me a time.

**Comment by 1024jp** [comment]
Based on my investigation, this seems to be a system-side issue.
When I open Apple Pages in the same manner, it exhibits the same behavior.

```sh
/Applications/Pages.app/Contents/MacOS/Pages
```

So, could you report it to Apple as well?
https://feedbackassistant.apple.com

I’ll also send feedback later.

In this connection, I tried TextEdit too, but it got killed immediately. I'm not sure what happened with that one.

```sh
/System/Applications/TextEdit.app/Contents/MacOS/TextEdit
zsh: killed     /System/Applications/TextEdit.app/Contents/MacOS/TextEdit
```

**Comment by chrisbergeron** [comment]
It looks like it does open, but it opens minimized.  Does that help at all?  I'm not a Swift dev, so I'm not sure about initial window paint, canvas on macos native.

**Comment by 1024jp** [comment]
> It looks like it does open, but it opens minimized.

Hmm, could you tell me how did you judge it?

I tried the same process with another computer and `/Applications/CotEditor.app/Contents/MacOS/CotEditor` worked.
Moreover, after that, I tried also the same process with the computer, I encountered the issue when I tested it the last time, and this time, it worked... 
So, it appears it has some specific conditions for reproducing the issue.
It can be related to #1933, but not sure.

By the way, I suppose calling the executable in Contents/MacOS/ directly is actually not a recommended way in the macOS world.
Instead, I recommend:

```sh
open /Applications/CotEditor.app 
```

or the built-in `cot` command.

https://coteditor.com/cot

**Comment by chrisbergeron** [comment]
Interesting - `open /Applications/CotEditor.app` load the app front and center the way I would like.

`cot` command and invoking `/Applications/CotEditor.app/Contents/MacOS/CotEditor` opens app minimized.

My macos version is: 15.7.2 (24G325)

**Comment by 1024jp** [comment]
Since #1933 appears to stem from the same issue, I've consolidated the problem into this thread, which is written in English for other users.

The `cot` command just uses `osascript` to launch CotEditor.app.
So, theoretically, the outcome from calling `cot` and `open xxx.app` must be the same.
Therefore, regarding `cot` and `open`, I suspect the timing rather than the difference in the commands being called...

**Comment by 1024jp** [comment]
I’ve sent a feedback regarding this issue to Apple: [FB21087054](https://github.com/1024jp/AppleFeedback/issues/87)

**Comment by 1024jp** [comment]
Posted on Apple Developer Forum as well: https://developer.apple.com/forums/thread/807805

**Comment by 1024jp** [comment]
@chrisbergeron I received a response from an Apple engineer.
According to them, this appears to be an issue on the macOS side, and there is unfortunately no practical workaround available for third-party applications.
Because of this, we will likely need to wait for a fix in macOS.
Since Apple is now aware of the problem, I hope it will be addressed in a future update.

From the CotEditor project’s perspective, I’ll close this ticket for now, as there is nothing more actionable we can do at the application level.
However, if I discover any additional information or conditions that could help Apple identify the cause, I will forward it to them.

**Comment by charonferry** [comment]
@1024jp 

from #1933 
本日(12/13)リリースされたmacOS 26.2でも依然、問題が発生します。
ご連絡まで。

This issue occurs in macOS 26.2 released today (Dec 13, JST).

**Comment by 1024jp** [comment]
@charonferry 残念ながらAppleは他の開発者から受けたバグ報告を即座に修正するとは限らず、何年もかかる場合もあります。その間我々にできることはほとんどありません。

Unfortunately, Apple doesn't always fix bug reports submitted by other developers immediately; sometimes it can take years. During that time, there's little we can do.

**Comment by charonferry** [comment]
@1024jp 
本日(9/15)リリースされたmacOS 27で問題が発生するか試しました。
本件が解決された可能性があります。
再度試して、報告します。
連絡まで。

I tested whether this issue occurs in macOS 27, which was released today (15 Sep. JST).
It's possible this problem has been resolved.
I'll try again, and report.

**Comment by 1024jp** [comment]
@charonferry Unfortunately, I suppose it still doesn’t fix on macOS 27. The status of my feedback to Apple hasn’t been changed as well.

**Comment by chrisbergeron** [comment]
Thank you for trying.  It's appreciated.
