### ISSUE TITLE
A problem about scripts on macOS 10.13 High Sierra with CotEditor 3.2.2

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#733]
On macOS 10.13 High Sierra with CotEditor 3.2.2, I found a problem about scripts.

I tried the following process after uninstalling CotEditor with AppCleaner and reinstalling CotEditor from AppStore.

1. Open a markdown text file, and run the following ruby script. It works as I intend.

> #!/usr/bin/env ruby -Ku
> #%%%{CotEditorXInput=AllText}%%%
> #%%%{CotEditorXOutput=Pasteboard}%%%
> 
> while $stdin.gets
>   print "- " + $1 if /^## ?([^#]+)/ =~ $_ 
> end

2. However, when I run the script again, it doesn't work. The result is none.

3. The same phenomenon occur with other scripts. They work once, but don't work again. I have to quit and run CotEditor to work a script.

These problem didn't occur on macOS 10.12 with CotEditor 3.2.1.

**Comment by 1024jp** [comment]
Thank you for the bug report and sorry for the bug.
I've just reproduced the issue under my environment.
I'll try to fix.

**Comment by 1024jp** [comment]
I've fixed this issue.
The fix is going to be included to CotEditor 3.2.3 that I may release at the end of this month.

Thank you for your feedback again :)

**Comment by tatsy-ymj** [comment]
I still have the problem with scripts.

1. Open a markdown text file, and run the following ruby script. It works as I intend.

```
#!/usr/bin/env ruby -Ku
#%%%{CotEditorXInput=AllText}%%%
#%%%{CotEditorXOutput=Pasteboard}%%%

while $stdin.gets
print "- " + $1 if /^## ?([^#]+)/ =~ $_
end
```

2. The above script works well with text files which have less than 21962 characters (UTF-8), but doesn't work with text files which have more than 21963 characters. 

I attach test files and a movie.
[script_test.zip](https://github.com/coteditor/CotEditor/files/1406593/script_test.zip)
https://drive.google.com/file/d/0B0emCo_bF-igSGYzSWwxaXVpclk/view?usp=sharing
